trigger:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: githubRepo
      type: github
      name: ankitbarlota92/ProductsAndOrders
      ref: refs/heads/main
      endpoint: github-connection

variables:
  acrLoginServer: 'stackrouteprdsandorders.azurecr.io'
  dockerRegistryServiceConnection: 'stackroute-acr-connection2'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Images
  jobs:
  - job: Build
    displayName: Build and Push Images
    pool:
      name: Default  # Use self-hosted agent in Default pool

    steps:
    - checkout: githubRepo

    # Build and push ProductService
    - task: Docker@2
      displayName: Build ProductService image
      inputs:
        command: build
        repository: $(acrLoginServer)/productservice
        Dockerfile: 'Dockerfile.productservice'
        tags: |
          $(Build.BuildId)
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: Push ProductService image
      inputs:
        command: push
        repository: $(acrLoginServer)/productservice
        tags: |
          $(Build.BuildId)
        containerRegistry: $(dockerRegistryServiceConnection)

    # Build and push OrderService
    - task: Docker@2
      displayName: Build OrderService image
      inputs:
        command: build
        repository: $(acrLoginServer)/orderservice
        Dockerfile: 'Dockerfile.orderservice'
        tags: |
          $(Build.BuildId)
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: Push OrderService image
      inputs:
        command: push
        repository: $(acrLoginServer)/orderservice
        tags: |
          $(Build.BuildId)
        containerRegistry: $(dockerRegistryServiceConnection)

